prSections:
  - title: Needs Team Review
    filters: is:open team-review-requested:ef-global/global-creative-devs draft:false -author:@me -org:eftours
  - title: Needs My Review
    filters: is:open review-requested:@me draft:false -author:@me -org:eftours
  - title: Mine not reviewed @ef-global
    filters: is:open author:@me review:none draft:false org:ef-global
  - title: Mine reviewed @ef-global
    filters: type:pr is:open author:@me draft:false user:ef-global -review:none
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me draft:false -org:eftours
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Backpack
    filters: is:open repo:ef-global/backpack
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 30
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: ""
confirmQuit: false
smartFilteringAtLaunch: false